# Generated by Django 3.2 on 2021-04-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_owner_date_crated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='post/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='accounts.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_Owner', to='accounts.owner')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.posts')),
            ],
        ),
    ]
