# Generated by Django 3.2 on 2021-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210413_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_crated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
